apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
  namespace: default
  labels:
    app: cpu-stress
    team: data-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
        team: data-pipeline
    spec:
      containers:
        - name: stress
          image: polinux/stress
          command: ["stress"]
          args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "150M", "--timeout", "99999s"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "200Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
  namespace: default
  labels:
    app: memory-hog
    team: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
        team: data-pipeline
    spec:
      containers:
        - name: memory-hog
          image: polinux/stress
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "256M", "--timeout", "99999s"]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-app
  namespace: default
  labels:
    app: crashloop-app
    team: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-app
  template:
    metadata:
      labels:
        app: crashloop-app
        team: backend
    spec:
      containers:
        - name: crash
          image: busybox:latest
          command: ["/bin/sh", "-c", "echo 'Starting...'; sleep 15; echo 'Crashing!'; exit 1"]
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "50m"
              memory: "32Mi"
